// Generated by CoffeeScript 2.7.0
(function() {
  var contas, crypto, dados, error, fs, gerarHash, readline, yaml;

  crypto = require('crypto');

  readline = require('readline').createInterface({
    input: process.stdin,
    output: process.stdout
  });

  fs = require('fs');

  yaml = require('js-yaml');

  module.exports = { gerarHash };

  gerarHash = function(senha) {
    return crypto.createHash('sha256').update(senha).digest('hex');
  };

  try {
    dados = fs.readFileSync('contas.yaml', 'utf8');
    contas = yaml.load(dados) || [];
  } catch (error1) {
    error = error1;
    contas = [];
  }

  readline.question('Digite seu login: ', function(login) {
    var existe;
    existe = contas.find(function(conta) {
      return conta.login === login;
    });
    if (existe) {
      console.log('Erro: usuário já cadastrado');
      readline.close();
      return;
    }
    return readline.question('Digite sua senha: ', function(senha) {
      var novaConta, senhaHash, yamlString;
      senhaHash = gerarHash(senha);
      novaConta = {
        login: login,
        senha_hash: senhaHash
      };
      contas.push(novaConta);
      try {
        yamlString = yaml.dump(contas);
        fs.writeFileSync('contas.yaml', yamlString, 'utf8');
        console.log('Usuário cadastrado com sucesso!');
      } catch (error1) {
        error = error1;
        console.log('Erro ao salvar o arquivo: ', error);
      }
      return readline.close();
    });
  });

}).call(this);

