// Generated by CoffeeScript 2.7.0
(function() {
  // pede login e senha
  // verifica com o arquivo contas.yaml
  //mostra mensagem se login deu certo ou não
  // bonus: toca o som da MINHA VOZ falando mensagem "bem-vindo"
  var child_process, contas, crypto, dados, error, fs, gerarHash, readline, yaml;

  fs = require('fs');

  yaml = require('js-yaml');

  crypto = require('crypto');

  child_process = require('child_process');

  readline = require('readline').createInterface({
    input: process.stdin,
    output: process.stdout
  });

  gerarHash = require('./cadastrodeusuario.js');

  try {
    //leitura do arquivo yaml
    dados = fs.readFileSync('contas.yaml', 'utf8');
    contas = yaml.load(dados) || [];
  } catch (error1) {
    error = error1;
    console.log('Arquivo contas.yaml não encontrado');
    process.exit();
  }

  //perguntar login
  readline.question('Digite seu login: ', function(login) {
    return readline.question('Digite sua senha: ', function(senha) {
      var senhaHash, usuario;
      senhaHash = gerarHash(senha);
      usuario = contas.find(function(conta) {
        return conta.login === login && conta.senha_hash === senhaHash;
      });
      if (usuario) {
        console.log('Login bem-sucedido. Bem vindo, #{login}!');
      } else {
        console.log('Login inválido. Tente novamente.');
      }
      return readline.close();
    });
  });

}).call(this);

